### ISSUE TITLE
Incorrect curl command to download compose files

### ISSUE THREAD

**Issue by Akshit8** [cadence-workflow/Cadence-Docs#230]
Hi, So in reference to this [issue](https://github.com/cadence-workflow/Cadence-Docs/issues/171). I think it still persists. So running the curl command mentioned in the docs

```sh
curl -O https://raw.githubusercontent.com/cadence-workflow/cadence/master/docker/docker-compose.yml && curl -O https://raw.githubusercontent.com/cadence-workflow/cadence/master/docker/prometheus/prometheus.yml
```
This only downloads `docker-compose.yml` and `promethues.yml` 

```
.
├── docker-compose.yml
└── prometheus.yml
```

But inside `docker-compose.yml` it clearly has these volumes under promethues and grafana service. Prometheus looks for `prometheus.yml` inside promethues directory and Grafana looks for `grafana.ini` inside grafana directory. Both of these are not downloaded with above curl command.

```yml
...
prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
....
grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/etc/grafana
    user: "1000"
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
```
